"""What moved on the leaderboard since the last snapshot, written for skimming."""

from __future__ import annotations

INDEX_MOVE = 1.0   # index points; smaller wobbles are re-run noise
COST_MOVE = 0.10   # 10% change in $/task


def diff(prev: dict | None, new: dict) -> tuple[list[str], list[str]]:
    """Returns (changelog lines, notices for a human). Rows are keyed by label."""
    if not prev:
        return (["Initial snapshot."], [])
    old = {r["label"]: r for r in prev["rows"]}
    cur = {r["label"]: r for r in new["rows"]}
    rank = {r["label"]: i for i, r in enumerate(new["rows"], 1)}
    lines: list[str] = []
    notices: list[str] = []
    for label in sorted(cur.keys() - old.keys(), key=lambda k: rank[k]):
        r = cur[label]
        lines.append(f"- New: **{label}** at #{rank[label]}, index {r['index']}.")
        notices.append(f"{label} was added to the leaderboard (#{rank[label]}, index {r['index']}). "
                       f"Does its model need notes in references/models/?")
    for label in sorted(old.keys() - cur.keys()):
        lines.append(f"- Removed: {label} (was index {old[label]['index']}).")
    for label in sorted(old.keys() & cur.keys(), key=lambda k: rank[k]):
        a, b = old[label], cur[label]
        if abs(b["index"] - a["index"]) >= INDEX_MOVE:
            lines.append(f"- {label}: index {a['index']} -> {b['index']} (now #{rank[label]}).")
        if a.get("cost_usd") and b.get("cost_usd") and abs(b["cost_usd"] - a["cost_usd"]) / a["cost_usd"] >= COST_MOVE:
            lines.append(f"- {label}: ${a['cost_usd']} -> ${b['cost_usd']} per task.")
    if prev.get("index_version") != new.get("index_version"):
        lines.insert(0, f"- Index methodology changed: {prev.get('index_version')} -> {new.get('index_version')}. "
                        "Scores before and after are not comparable.")
    return lines, notices


def update_changelog(existing: str, day: str, lines: list[str], keep: int = 30) -> str:
    header = ("# Changelog\n\n<!-- GENERATED by pipeline/diff.py. Last 30 entries; git history is the archive. -->\n\n"
              "What moved on the coding-agent leaderboard.\n")
    sections: list[str] = []
    if existing:
        sections = ["## " + p.rstrip() for p in existing.split("\n## ")[1:] if not p.startswith(day)]
    if lines:
        sections.insert(0, f"## {day}\n\n" + "\n".join(lines))
    return header + "\n" + "\n\n".join(sections[:keep]) + "\n"
