"""Compare yesterday's snapshot to today's and describe what moved.

Output is written for skimming ("Grok 4.7 added to Epoch ECI at 158.2"), not
for completeness: the full history is git. Thresholds keep noise out; a 0.3
point wobble in an Elo is not news.
"""

from __future__ import annotations

THRESHOLDS = {"index": 2.0, "elo": 15.0, "%": 2.0, "score": 0.02}
PRICE_PCT = 0.05


def _key(s: dict) -> tuple:
    return (s["board"], s["model"], s["variant"])


def diff(prev: dict | None, new: dict) -> tuple[list[str], list[str]]:
    """Returns (changelog lines, new-model notices for the human)."""
    if not prev:
        return (["Initial snapshot."], [])
    lines: list[str] = []
    notices: list[str] = []
    name = lambda mid: new["models"].get(mid, prev["models"].get(mid, {})).get("display", mid)  # noqa: E731

    old = {_key(s): s for s in prev["scores"]}
    cur = {_key(s): s for s in new["scores"]}

    # A model's first score anywhere is the signal that a human should write
    # or review its prose, so it also becomes a notice (-> GitHub issue).
    had_any = {s["model"] for s in prev["scores"]}
    for k in sorted(cur.keys() - old.keys()):
        s = cur[k]
        lines.append(f"- {name(s['model'])}: new {s['board']} score, {s['variant']} = {s['value']}{_u(s)}.")
        if s["model"] not in had_any:
            notices.append(f"{name(s['model'])} got its first score ({s['board']}). Review references/models/{s['model']}.md.")
            had_any.add(s["model"])
    for k in sorted(old.keys() - cur.keys()):
        s = old[k]
        lines.append(f"- {name(s['model'])}: {s['board']} score for {s['variant']} disappeared upstream (was {s['value']}{_u(s)}).")
    for k in sorted(old.keys() & cur.keys()):
        a, b = old[k], cur[k]
        if abs(b["value"] - a["value"]) >= THRESHOLDS.get(b["unit"], 2.0):
            lines.append(f"- {name(b['model'])}: {b['board']} {b['variant']} {a['value']} -> {b['value']}{_u(b)}.")

    for mid, m in new["models"].items():
        f0 = prev["models"].get(mid, {}).get("facts", {})
        f1 = m.get("facts", {})
        for k, label in (("price_in", "input price"), ("price_out", "output price")):
            x, y = f0.get(k), f1.get(k)
            if x and y and abs(y - x) / x >= PRICE_PCT:
                lines.append(f"- {m['display']}: {label} ${x} -> ${y} per 1M.")
        if f1 and not f0:
            lines.append(f"- {m['display']}: now listed on models.dev.")
    for src, meta in new["sources"].items():
        if meta.get("stale") and not prev["sources"].get(src, {}).get("stale"):
            lines.append(f"- {meta['name']}: fetch failed, keeping data from {meta['as_of']}.")
    return lines, notices


def _u(s: dict) -> str:
    return "%" if s["unit"] == "%" else ""


def update_changelog(existing: str, day: str, lines: list[str], keep_days: int = 30) -> str:
    """Prepend today's section; keep the last `keep_days` dated sections."""
    header = ("# Changelog\n\n<!-- GENERATED by pipeline/diff.py. Last 30 days; git history is the archive. -->\n\n"
              "What moved in the nightly data. Skim this after a lab release.\n")
    sections: list[str] = []
    if existing:
        parts = existing.split("\n## ")[1:]
        sections = ["## " + p.rstrip() for p in parts if not p.startswith(day)]
    if lines:
        sections.insert(0, f"## {day}\n\n" + "\n".join(lines))
    return header + "\n" + "\n\n".join(sections[:keep_days]) + "\n"
