"""Read the human prose layer and flag what needs a human.

The nightly job NEVER edits prose. It only reads the frontmatter to build the
model index and to open "stale prose" issues. If an LLM ever rewrites these
files automatically, the guide becomes averaged Twitter; that is the one
failure this repo exists to avoid.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

REQUIRED = ("id", "display", "reviewed", "review_by", "status", "superseded_by")
STATUSES = {"provisional", "settled", "legacy"}


def read_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    fm = yaml.safe_load(text.split("---\n", 2)[1]) or {}
    missing = [k for k in REQUIRED if k not in fm]
    if missing:
        raise ValueError(f"{path}: frontmatter missing {missing}")
    if fm["status"] not in STATUSES:
        raise ValueError(f"{path}: status must be one of {sorted(STATUSES)}")
    for k in ("reviewed", "review_by"):
        if isinstance(fm[k], str):
            fm[k] = date.fromisoformat(fm[k])
    return fm


def load_dir(models_dir: Path) -> tuple[dict[str, dict], list[str]]:
    """Read every <id>.md in models_dir. Returns ({id: frontmatter}, problems)."""
    prose: dict[str, dict] = {}
    problems: list[str] = []
    for p in sorted(models_dir.glob("*.md")):
        if p.name.startswith("_"):
            continue
        try:
            fm = read_frontmatter(p)
        except ValueError as e:
            problems.append(str(e))
            continue
        if fm["id"] != p.stem:
            problems.append(f"{p.name}: frontmatter id {fm['id']!r} != filename")
        prose[fm["id"]] = fm
    for mid, fm in prose.items():
        if fm.get("superseded_by") and fm["superseded_by"] not in prose:
            problems.append(f"{mid}: superseded_by {fm['superseded_by']!r} has no notes file")
    return prose, problems


def stale(prose: dict[str, dict], today: date) -> list[str]:
    return sorted(mid for mid, fm in prose.items() if fm["review_by"] < today)


def render_index(prose: dict[str, dict], today: date) -> str:
    out = ["# Models with notes", "",
           "<!-- GENERATED by pipeline/prose.py from each file's frontmatter. Do not edit by hand. -->", "",
           "Human notes exist for these models. A model on the leaderboard without notes here has scores only.", "",
           "`provisional` = released recently, notes rest on launch-week evidence. `legacy` = superseded. "
           "STALE = past its review date: say so when quoting it.", "",
           "| Model | Id | Status | Last human review | Notes |", "|---|---|---|---|---|"]
    for mid, fm in sorted(prose.items(), key=lambda kv: kv[1]["display"].lower()):
        flag = " **STALE**" if fm["review_by"] < today else ""
        sup = f" (superseded by `{fm['superseded_by']}`)" if fm.get("superseded_by") else ""
        out.append(f"| {fm['display']} | `{mid}` | {fm['status']}{sup}{flag} | {fm['reviewed']} | [{mid}.md]({mid}.md) |")
    out.append("")
    return "\n".join(out)
