"""Read the human prose layer and flag what needs a human.

The nightly job NEVER edits prose. It only reads the frontmatter to build the
model index and to open "stale prose" issues. If an LLM ever rewrites these
files automatically, the guide becomes averaged Twitter; that is the one
failure this repo exists to avoid.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

REQUIRED = ("id", "display", "reviewed", "review_by", "status", "superseded_by")
STATUSES = {"provisional", "settled", "legacy"}


def read_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    fm = yaml.safe_load(text.split("---\n", 2)[1]) or {}
    missing = [k for k in REQUIRED if k not in fm]
    if missing:
        raise ValueError(f"{path}: frontmatter missing {missing}")
    if fm["status"] not in STATUSES:
        raise ValueError(f"{path}: status must be one of {sorted(STATUSES)}")
    for k in ("reviewed", "review_by"):
        if isinstance(fm[k], str):
            fm[k] = date.fromisoformat(fm[k])
    return fm


def load_all(models_dir: Path, allow_ids: list[str]) -> tuple[dict[str, dict], list[str]]:
    """Returns ({id: frontmatter}, problems). Every allowlisted model must have prose."""
    prose: dict[str, dict] = {}
    problems: list[str] = []
    for mid in allow_ids:
        p = models_dir / f"{mid}.md"
        if not p.exists():
            problems.append(f"{mid}: no prose file at {p.relative_to(models_dir.parent.parent)}")
            continue
        fm = read_frontmatter(p)
        if fm["id"] != mid:
            problems.append(f"{p.name}: frontmatter id {fm['id']!r} != filename")
        prose[mid] = fm
    return prose, problems


def stale(prose: dict[str, dict], today: date) -> list[str]:
    return sorted(mid for mid, fm in prose.items() if fm["review_by"] < today)


def render_index(snap: dict, prose: dict[str, dict], today: date) -> str:
    out = ["# Models covered", "",
           "<!-- GENERATED by pipeline/prose.py from each file's frontmatter. Do not edit by hand. -->", "",
           "Only these models are covered. If the user asks about another model, say it is not in this guide.", "",
           "`provisional` = released recently, notes are mostly launch-week evidence. `legacy` = superseded; kept for comparison. "
           "A model marked STALE has notes past their review date: say so when you quote them.", "",
           "| Model | Id | Lab | Tier | Status | Last human review | Notes |", "|---|---|---|---|---|---|---|"]
    for mid, m in snap["models"].items():
        fm = prose.get(mid)
        if not fm:
            out.append(f"| {m['display']} | `{mid}` | {m['lab']} | {m['tier']} | no notes yet | - | - |")
            continue
        flag = " **STALE**" if fm["review_by"] < today else ""
        sup = f" (superseded by `{fm['superseded_by']}`)" if fm.get("superseded_by") else ""
        out.append(f"| {m['display']} | `{mid}` | {m['lab']} | {m['tier']} | {fm['status']}{sup}{flag} | {fm['reviewed']} | [{mid}.md]({mid}.md) |")
    out.append("")
    return "\n".join(out)
