"""Render the parsed leaderboard into the one table agents read.

No timestamps except the source's own as-of date, so an unchanged leaderboard
renders byte-identical files and the nightly job commits nothing.
"""

from __future__ import annotations

from . import aa

NA = "n/a"


def _v(x, fmt: str) -> str:
    return NA if x is None else fmt.format(x)


def render_table(data: dict) -> str:
    rows = data["rows"]
    evals = list(aa.EVALS)
    out = [
        "# Coding agents leaderboard",
        "",
        "<!-- GENERATED by pipeline/render.py. Do not edit by hand. -->",
        "",
        f"**Source:** Artificial Analysis, [Coding Agent Index {data['index_version']}](https://artificialanalysis.ai/agents/coding-agents). "
        f"**Data as of:** {data['as_of'] or 'unknown'}.",
        "",
        "Each row is an agent product running one model at one effort level. The index is the average of the three evals "
        "(pass rate, %). Cost and time are per task, averaged. Refusal = share of attempts the model refused on safety grounds. "
        "\"Alt config\" rows are non-default setups the page also measured.",
        "",
        "| # | Agent | Model (effort) | Index | " + " | ".join(aa.EVALS[e] for e in evals) + " | $ / task | Min / task | Refusal |",
        "|---|---|---|---|" + "---|" * len(evals) + "---|---|---|",
    ]
    for i, r in enumerate(rows, 1):
        model = r["model"] + ("" if r["default_config"] else " *(alt config)*") + (" *(unavailable)*" if r["unavailable"] else "")
        cells = [str(i), r["agent"], model, f"**{r['index']:.1f}**"]
        cells += [_v(r["evals"].get(e), "{:.1f}") for e in evals]
        cells += [_v(r["cost_usd"], "${:.2f}"), _v(r["minutes"], "{:.0f}"), _v(r["refusal_pct"], "{:.1f}%")]
        out.append("| " + " | ".join(c.replace("|", "/") for c in cells) + " |")

    # Two derived views that answer the most common follow-up questions
    # without the agent doing arithmetic on the big table.
    priced = [r for r in rows if r["cost_usd"]]
    out += ["", "## Best score for the money", "",
            "Index points per dollar per task. Only meaningful between setups that are good enough for the job.", "",
            "| Agent | Model (effort) | Index | $ / task | Index per $ |", "|---|---|---|---|---|"]
    for r in sorted(priced, key=lambda r: (-r["index"] / r["cost_usd"], r["label"]))[:8]:
        out.append(f"| {r['agent']} | {r['model']} | {r['index']:.1f} | ${r['cost_usd']:.2f} | {r['index'] / r['cost_usd']:.0f} |")

    timed = [r for r in rows if r["minutes"]]
    out += ["", "## Fastest", "", "| Agent | Model (effort) | Index | Min / task |", "|---|---|---|---|"]
    for r in sorted(timed, key=lambda r: (r["minutes"], r["label"]))[:8]:
        out.append(f"| {r['agent']} | {r['model']} | {r['index']:.1f} | {r['minutes']:.0f} |")

    out += ["", "---", "", "Source: Artificial Analysis (artificialanalysis.ai), Coding Agent Index. All credit for the measurements is theirs.", ""]
    return "\n".join(out)
