"""Render data/snapshot.json into the markdown tables agents read.

Design rules (they are the product, see SKILL.md):
- One file per job so an agent loads only what it needs; never one mega-table.
- Every number carries the upstream's own configuration label (effort level,
  harness). A score without its effort level is how comparisons lie.
- Missing data is listed as "not yet measured", never interpolated.
- Independent and vendor-reported numbers never share a table.
- No timestamps except each source's own as-of date, so unchanged upstream
  data renders byte-identical files.
"""

from __future__ import annotations

from collections import defaultdict

BOARDS = {
    "epoch.eci": ("Epoch Capabilities Index (ECI)", "Epoch's composite across its benchmark suite. Higher is better. Scale is Epoch's own, not a percentage."),
    "epoch.gpqa_diamond": ("GPQA Diamond (Epoch-run)", "Graduate-level science multiple choice. Near saturation at the frontier."),
    "epoch.frontiermath_t1_3": ("FrontierMath Tiers 1-3 v2 (Epoch-run)", "Hard research-style math, private set."),
    "epoch.simpleqa_verified": ("SimpleQA Verified (Epoch-run)", "Short factual recall. A rough proxy for how often a model knows vs. guesses."),
    "epoch.swe_bench_verified": ("SWE-bench Verified (Epoch-run)", "Real GitHub issues, fixed by the model in Epoch's own harness. Not comparable to lab-reported SWE-bench numbers."),
    "epoch.deepswe": ("DeepSWE (Datacurve, via Epoch)", "Agentic software-engineering tasks, pass@1, in the named harness. Independent of the model labs."),
    "epoch.frontierswe": ("FrontierSWE (via Epoch)", "Hard, long software-engineering tasks mixing implementation, performance and research work. Independent."),
    "epoch.cursorbench": ("CursorBench (Cursor, via Epoch)", "Cursor's own eval of real editor coding tasks, per reasoning level. Run by an IDE vendor, not a model lab."),
    "epoch.mirrorcode": ("MirrorCode (Epoch-run)", "Epoch's long-horizon coding benchmark."),
    "epoch.terminalbench_2": ("Terminal-Bench 2.0 (via Epoch)", "Terminal tasks. Best agent harness per configuration; the harness is named because it moves scores a lot."),
    "epoch.osworld_2": ("OSWorld 2.0 (official results, via Epoch)", "Computer use in real desktop apps. Binary = task fully done; partial credit shown alongside."),
    "lmarena.text": ("LMArena Text (human preference Elo)", "Blind pairwise votes on chat answers. Measures what people prefer, not correctness."),
    "lmarena.webdev": ("LMArena WebDev (human preference Elo)", "Blind votes on generated web apps. The best public signal for frontend/UI taste."),
    "lmarena.agent": ("LMArena Agent Arena", "Preference score for agentic sessions. Scores are relative (can be negative)."),
    "steel.osworld2": ("OSWorld 2.0 (Steel compilation, mostly vendor-reported)", "Lab-published numbers. Harnesses, step budgets and task sets differ; read the notes."),
    "steel.osworld": ("OSWorld-Verified (Steel compilation, mostly vendor-reported)", "Lab-published numbers on the older OSWorld-Verified set."),
}

NA = "n/a"


def _fmt(v, unit: str) -> str:
    if v is None:
        return NA
    if unit == "%":
        return f"{v:.1f}%"
    if unit == "elo":
        return f"{v:.0f}"
    if unit == "index":
        return f"{v:.1f}"
    return f"{v:.3f}"


def _money(v) -> str:
    return NA if v is None else (f"${v:.2f}" if v >= 0.1 else f"${v:.3f}")


def _ctx(v) -> str:
    if not v:
        return NA
    return f"{v / 1_000_000:.2f}M".replace(".00M", "M") if v >= 1_000_000 else f"{v // 1000}K"


def _header(title: str, snap: dict, sources: list[str], intro: str) -> list[str]:
    dates = " · ".join(f"{snap['sources'][s]['name']} {snap['sources'][s]['as_of']}" + (" (STALE: last fetch failed)" if snap['sources'][s].get('stale') else "")
                       for s in sources if s in snap["sources"])
    return [
        f"# {title}",
        "",
        "<!-- GENERATED by pipeline/render.py from data/snapshot.json. Do not edit by hand. -->",
        "",
        f"**Data as of:** {dates}",
        "",
        intro,
        "",
    ]


def _footer(snap: dict, sources: list[str]) -> list[str]:
    out = ["---", "", "Sources and licences:"]
    for s in sources:
        m = snap["sources"].get(s)
        if m:
            out.append(f"- {m['name']} ({m['license']}): {m['url']}")
    out.append("")
    return out


def _board_section(snap: dict, board: str, *, max_other: int = 3, extra_col=None) -> list[str]:
    title, blurb = BOARDS[board]
    rows = [s for s in snap["scores"] if s["board"] == board]
    by_model: dict[str, list[dict]] = defaultdict(list)
    for s in rows:
        by_model[s["model"]].append(s)
    out = [f"## {title}", "", blurb, ""]
    if not by_model:
        out += ["No allowlisted model has a score here yet.", ""]
        return out
    head = "| # | Model | Best | Configuration |" + (f" {extra_col[0]} |" if extra_col else "") + " Other configurations |"
    out += [head, "|" + "---|" * (head.count("|") - 1)]
    ranked = sorted(by_model.items(), key=lambda kv: (-max(x["value"] for x in kv[1]), kv[0]))
    for i, (mid, ss) in enumerate(ranked, 1):
        ss = sorted(ss, key=lambda x: (-x["value"], x["variant"]))
        best, others = ss[0], ss[1:1 + max_other]
        other = "; ".join(f"{o['variant']} {_fmt(o['value'], o['unit'])}" for o in others) or "-"
        if len(ss) > 1 + max_other:
            other += f"; +{len(ss) - 1 - max_other} more in snapshot.json"
        cells = [str(i), snap["models"][mid]["display"], _fmt(best["value"], best["unit"]), best["variant"]]
        if extra_col:
            cells.append(extra_col[1](best))
        cells.append(other)
        out.append("| " + " | ".join(c.replace("|", "/") for c in cells) + " |")
    missing = [snap["models"][m]["display"] for m in snap["models"] if m not in by_model]
    out += ["", f"Not yet measured here: {', '.join(missing) if missing else 'none'}.", ""]
    return out


def render_overall(snap: dict) -> str:
    best = lambda mid, board: max((s for s in snap["scores"] if s["model"] == mid and s["board"] == board),  # noqa: E731
                                  key=lambda s: s["value"], default=None)
    rows = []
    for mid, m in snap["models"].items():
        eci, arena = best(mid, "epoch.eci"), best(mid, "lmarena.text")
        f = m["facts"]
        rows.append((-(eci["value"] if eci else -1), -(arena["value"] if arena else -1), m["display"],
                     [m["display"], m["tier"], _fmt(eci["value"], "index") if eci else NA,
                      f"{_fmt(arena['value'], 'elo')} ({arena['variant']})" if arena else NA,
                      f"{_money(f.get('price_in'))} / {_money(f.get('price_out'))}" if f else NA,
                      _ctx(f.get("context")) if f else NA]))
    rows.sort()
    out = _header("Overall leaderboard", snap, ["epoch", "lmarena", "models_dev"],
                  "One row per allowlisted model, ordered by Epoch's ECI (models without an ECI yet go last, by Arena Elo). "
                  "ECI is a capability composite; Arena Elo is human preference. They disagree on purpose: read both. "
                  "For a specific job open that job's table instead of ranking from this page.")
    out += ["| Model | Tier | ECI (Epoch) | LMArena Text Elo (config) | $ in / out per 1M | Context |", "|---|---|---|---|---|---|"]
    out += ["| " + " | ".join(r[3]) + " |" for r in rows]
    out.append("")
    for b in ("epoch.gpqa_diamond", "epoch.frontiermath_t1_3", "epoch.simpleqa_verified"):
        out += _board_section(snap, b)
    return "\n".join(out + _footer(snap, ["epoch", "lmarena", "models_dev"]))


def render_coding(snap: dict) -> str:
    out = _header("Coding", snap, ["epoch", "lmarena"],
                  "Independent coding measurements only. Lab-reported SWE-bench / Terminal-Bench numbers are NOT here "
                  "(different harnesses, not comparable). Pair with references/pick-by-job.md for judgment.")
    harness = ("Harness", lambda s: s["extra"].get("agent", "") or "-")
    out += _board_section(snap, "epoch.cursorbench")
    out += _board_section(snap, "epoch.deepswe", extra_col=harness)
    out += _board_section(snap, "epoch.frontierswe", extra_col=harness)
    out += _board_section(snap, "epoch.swe_bench_verified")
    out += _board_section(snap, "epoch.terminalbench_2", extra_col=harness)
    out += _board_section(snap, "epoch.mirrorcode")
    out += _board_section(snap, "lmarena.webdev")
    return "\n".join(out + _footer(snap, ["epoch", "lmarena"]))


def render_agents(snap: dict) -> str:
    out = _header("Agents and tool use", snap, ["tau2", "lmarena", "epoch"],
                  "Multi-turn tool-use and agentic-session measurements. For terminal/coding agents also see tables/coding.md "
                  "(Terminal-Bench); for computer use see tables/computer-use.md.")
    rows = [s for s in snap["scores"] if s["board"].startswith("tau2.")]
    out += ["## tau2-bench (pass^1 per domain)", "",
            "Simulated customer-service conversations with tools and policies. pass^1 = share of tasks solved on a single try. "
            "Domains are not averaged here because submissions cover different domain sets.", ""]
    if rows:
        grid: dict[tuple, dict] = defaultdict(dict)
        meta: dict[tuple, dict] = {}
        for s in rows:
            k = (s["model"], s["variant"])
            grid[k][s["board"].split(".", 1)[1]] = s["value"]
            meta[k] = s["extra"]
        out += ["| Model | Configuration | Airline | Retail | Telecom | Banking | Submitted by | Date |", "|---|---|---|---|---|---|---|---|"]
        for k in sorted(grid, key=lambda k: (-(grid[k].get("telecom") or grid[k].get("airline") or 0), k)):
            g = grid[k]
            out.append("| " + " | ".join([snap["models"][k[0]]["display"], k[1]] +
                                         [_fmt(g.get(d), "%") for d in ("airline", "retail", "telecom", "banking_knowledge")] +
                                         [meta[k].get("submitted_by") or "-", meta[k].get("date") or "-"]) + " |")
        missing = [m["display"] for mid, m in snap["models"].items() if mid not in {k[0] for k in grid}]
        out += ["", f"Not yet measured here: {', '.join(missing)}.", ""]
    else:
        out += ["No allowlisted model has a tau2-bench submission yet.", ""]
    out += _board_section(snap, "lmarena.agent")
    return "\n".join(out + _footer(snap, ["tau2", "lmarena", "epoch"]))


def render_computer_use(snap: dict) -> str:
    out = _header("Computer and browser use", snap, ["epoch", "steel"],
                  "READ THIS FIRST: computer-use numbers are the least comparable scores in the field. Labs change the task set, "
                  "screen resolution, step budget and grader. Compare within one section only, never across sections, and prefer "
                  "the independent section when both have the model.")
    out += ["# Independent", ""]
    out += _board_section(snap, "epoch.osworld_2", extra_col=("Partial credit", lambda s: _fmt(s["extra"].get("partial"), "%")))
    out += ["# Vendor-reported (not independently verified)", ""]
    for b in ("steel.osworld2", "steel.osworld"):
        out += _board_section(snap, b, max_other=2, extra_col=("Source / notes", lambda s: f"[source]({s['extra'].get('source_url')}) {(s['extra'].get('notes') or '')[:140]}"))
    return "\n".join(out + _footer(snap, ["epoch", "steel"]))


def render_price(snap: dict) -> str:
    out = _header("Price, context and effort levels", snap, ["models_dev"],
                  "List prices in USD per 1M tokens from the first-party provider. Long-context prices apply above ~200K input tokens "
                  "where the provider charges more. **No speed / latency column:** no source we may redistribute publishes it; "
                  "see references/sources.md for how to get live speed numbers.")
    out += ["| Model | Tier | In | Out | Cache read | In / out >200K | Context | Max output | Effort levels | Open weights | Knowledge |",
            "|---|---|---|---|---|---|---|---|---|---|---|"]
    rows = []
    for mid, m in snap["models"].items():
        f = m["facts"]
        if not f:
            rows.append((9e9, m["display"], [m["display"], m["tier"]] + [NA] * 9))
            continue
        long = f"{_money(f['price_in_long'])} / {_money(f['price_out_long'])}" if f.get("price_in_long") else "-"
        rows.append((f.get("price_out") if f.get("price_out") is not None else 9e9, m["display"], [
            m["display"], m["tier"], _money(f.get("price_in")), _money(f.get("price_out")), _money(f.get("price_cache_read")),
            long, _ctx(f.get("context")), _ctx(f.get("max_output")), ", ".join(f.get("efforts") or []) or "-",
            "yes" if f.get("open_weights") else "no", f.get("knowledge") or NA]))
    rows.sort()
    out += ["| " + " | ".join(r[2]) + " |" for r in rows]
    out.append("")
    return "\n".join(out + _footer(snap, ["models_dev"]))


def render_meta(snap: dict) -> str:
    out = ["# Data freshness", "",
           "<!-- GENERATED by pipeline/render.py. Do not edit by hand. -->", "",
           "Each source's own as-of date. The nightly job refreshes these; if the newest date below is more than 7 days old, "
           "the tables may be stale (see SKILL.md step 1).", "",
           "| Source | Data as of | Licence | Allowlisted models covered |", "|---|---|---|---|"]
    for k in sorted(snap["sources"]):
        s = snap["sources"][k]
        stale = " (STALE: last fetch failed)" if s.get("stale") else ""
        out.append(f"| [{s['name']}]({s['url']}) | {s['as_of']}{stale} | {s['license']} | {len(s.get('present', []))} of {len(snap['models'])} |")
    out += ["", "## Attribution", "",
            "- Benchmark data: Epoch AI, CC BY 4.0 (epoch.ai/benchmarks). External rows keep their upstream licence (DATA-LICENSES.md).",
            "- Human-preference data: LMArena (lmarena.ai), CC BY 4.0.",
            "- Pricing and limits: models.dev, MIT.",
            "- Tool-use agents: tau2-bench (Sierra), MIT.",
            "- Computer-use compilation: Steel (leaderboard.steel.dev), MIT; mostly vendor-reported.", ""]
    return "\n".join(out)


def render_all(snap: dict) -> dict[str, str]:
    return {
        "_meta.md": render_meta(snap),
        "overall.md": render_overall(snap),
        "coding.md": render_coding(snap),
        "agents.md": render_agents(snap),
        "computer-use.md": render_computer_use(snap),
        "price-context.md": render_price(snap),
    }
